apiVersion: apps/v1
kind: Deployment
metadata:
  name: cni-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cni-test-deployment
  template:
    metadata:
      labels:
        app: cni-test-deployment
    spec:
      containers:
        - name: cni-container
          image: ifilyaninitmo/itdt-contained-frontend:master
          ports:
          - containerPort: 3000
          env:
            - name: REACT_APP_USERNAME
              value: "GhaithAbuHussain"
            - name: REACT_APP_COMPANY_NAME
              value: "itmo"
